---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: Getting current use running ansible
      shell: "whoami"
      register: current_ansible_user

    - name: Generating SSH key pair (if they don't exist)
      user:
        name: "{{ current_ansible_user.stdout }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        # ssh_key_passphrase: "{{ ssh_key_passphrase }}"
        force: no

    - name: Move k8cluster template file
      template:
        src: Requirements/templates/kubernetes.yaml
        dest: ../

- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: shh-copy-id to target nodes
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
