---
- name: Generating SSH key pair (if they don't exist)
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Getting current use running ansible
      shell: "whoami"
      register: current_ansible_user

    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "{{ current_ansible_user.stdout }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        # ssh_key_passphrase: "{{ ssh_key_passphrase }}"
        force: no
