---
- name: generate SSH key
  hosts: 127.0.0.1
  connection: local
  ansible_user: "{{ ansible_user }}"
  tasks:
    - name: Getting current user
      shell: "whoami"
      register: ansble_user

    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "{{ ansible_user.stdout }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        # ssh_key_passphrase: "{{ ssh_key_passphrase }}"
        force: no
