---
- name: Cleaning previous entries on /etc/hosts from ansible just hosts
  shell: |
    sed -i '/^# Ansible/,$d' /etc/hosts
  ignore_errors: yes

- name: Cleaning previous entries on /etc/hosts from ansible load_balanccer
  shell: |
    sed -i "/{{ apiserver_loadbalancer_address }}/d" /etc/hosts
  ignore_errors: yes