---
- name: Cleaning directories
  ansible.builtin.shell: |
    rm -rf "{{ item }}"
  with_items:
    - /var/log/messages-*
    - /opt/containerd 
    - /opt/cni 
    - /opt/kubespray 
    - /opt/mycluster
    - /opt/kube*
    - /opt/.*
    - /tmp/* 
    - /tmp/.*
    - /root/.ansible
    - /run/docker*
    - /etc/docker*
    - /etc/kuber*
    - /var/lib/etcd
    - /var/lib/dockershim/
    - /var/lib/containerd/
    - /var/lib/docker*
    - /usr/local/bin/kubernetes-scripts
    - /usr/local/bin/kube*
    - /usr/local/bin/calico*
    - /usr/local/bin/container*
    - /usr/local/bin/crict*
    - /usr/local/bin/runc
    - /usr/libexec/kuber*
  ignore_errors: True
  async: 900
  poll: 10