---
- name: Stopping all the Docker containers (if Docker exists)
  shell: |
    docker kill $(docker ps -a -q)
  ignore_errors: True
  async: 120
  poll: 10
  
- name: Removing all Docker containers (if Docker exists)
  shell: |
    docker rm $(docker ps -a -q)
  ignore_errors: True
  async: 120
  poll: 10
  
- name: Removing all Docker images (if Docker exists)
  shell: |
     docker rmi $(docker images -a -q)
  ignore_errors: True
  async: 180
  poll: 10
  
- name: Stopping Docker (if exists)
  shell: |
    systemctl stop docker --now
    systemctl disable docker --now
    systemctl stop docker.socket --now
    systemctl disable docker.socket --now
    pkill -9 -f docker
    pkill -9 -f docker*
  ignore_errors: True
  async: 120
  poll: 10

- name: Force Docker to stop
  shell: |
    pkill -9 -f docker
  ignore_errors: True
  async: 120
  poll: 10 
  
- name: Uninstalling previous versions of Docker (if exists)
  shell: |
    yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine podman runc
  ignore_errors: True
  async: 120
  poll: 10

- name: Unmounting /var/run/docker/*/* (if exists)
  shell: |
    umount /var/run/docker/*/*
  ignore_errors: True
  async: 180
  poll: 10

- name: Removing old Docker files (if exists)
  shell: |
    rm -rf /var/lib/docker /etc/docker/ /var/lib/containerd/ /run/docker* /etc/systemd/system/containerd.service*
  ignore_errors: True
  async: 120
  poll: 10