---
- name: Stopping ETCD
  shell: |
    systemctl stop etcd --now
  ignore_errors: True

- name: Disabling ETCD
  shell: |
    systemctl disable etcd --now
  ignore_errors: True

- name: Uninstalling previous versions of K8S(if present)
  shell: |
    yum remove -y etcd
  ignore_errors: True

- name: Removing /var/lib/etcd (If they exist)
  shell: |
    rm -rf /var/lib/etcd/ /etc/etcd /usr/local/bin/etc* /etc/systemd/system/etcd.service
  ignore_errors: True
