---
- name: Running "kubeadm reset", if k8s exists
  shell: |
    yes | yes | kubeadm reset
  ignore_errors: True

- name: "Stopping {{ item }}"
  shell: |
    systemctl stop {{ item }} --now
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  ignore_errors: True

- name: "Disabling {{ item }}"
  shell: |
    systemctl disable {{ item }} --now
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  ignore_errors: True

- name: Uninstalling previous versions of K8S(if present)
  shell: |
    yum remove -y kubeadm kubectl kubelet kubernetes-cni
  ignore_errors: True

- name: yum autoremove
  yum:
    autoremove: yes
  ignore_errors: True

- name: Removing ~/.kube
  shell: |
    rm -rf ~/.kube
  ignore_errors: True

- name: Removing /var/lib/kubelet /etc/kubernetes/ /var/lib/dockershim /var/run/kubernetes /var/lib/cni (If they exist)
  shell: |
    rm -rf /var/lib/kubelet/ /etc/kubernetes/* /etc/kubernetes/ /var/lib/dockershim/ /var/run/kubernetes/ /var/lib/cni/ /etc/cni/
  ignore_errors: True
