- name: Install required pacakges
  yum:
    name: yum-utils
    state: latest
  async: 600
  poll: 10

- name: Add Docker stable repo
  yum_repository:
    name: epel
    description: Docker stable
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

# - name: Upgrade all packages, excluding kernel
#   yum:
#     name: '*'
#     state: latest
#     exclude: kernel**