---
# vars file for automation KubeSpray
proxy_addr: "{{ proxy_addr }}"
no_proxy_addr: "{{ no_proxy_addr }}"
cluster_name: "{{ k8s_cluster_name }}"
apiserver_loadbalancer_domain_name: "{{ apiserver_loadbalancer_domain_name }}"
apiserver_loadbalancer_address: "{{ apiserver_loadbalancer_address }}"
apiserver_loadbalancer_port: "{{ apiserver_loadbalancer_port }}"
use_internal_loadbalancer: "{{ use_internal_loadbalancer }}"
internal_loadbalancer: "{{ internal_loadbalancer }}"
k8s_network_plugin: "{{ k8s_network_plugin }}"
container_runtime: "{{ container_runtime }}"

# File from KubeSpray kubeSpray/inventory/mycluster/group_vars/all/all.yaml
etcd_data_dir: "{{ etcd_data_dir | default('/var/lib/etcd') }}"
bin_dir: "{{ bin_dir | default('/usr/local/bin') }}"

# File from KubeSpray kubeSpray/inventory/mycluster/group_vars/k8s_cluster/k8s_cluster.yaml
kube_config_dir: /etc/kubernetes/
kube_cert_dir: "{{ kube_config_dir }}/ssl"
local_release_dir: "{{ local_release_dir }}"
kube_service_addresses: "{{ kube_service_addresses }}"
kube_pods_subnet: "{{ kube_pods_subnet }}"
credentials_dir: "{{ inventory_dir }}/credentials"
default_kubelet_config_dir: "{{ kube_config_dir }}/dynamic_kubelet_dir"

inventory_dir: inventory/local-dind/
