---
# vars file for automation KubeSpray
proxy_addr: "{{ proxy_addr }}"
no_proxy_addr: "{{ no_proxy_addr }}"
k8s_cluster_name: "{{ k8s_cluster_name }}"
apiserver_loadbalancer_domain_name: "{{ apiserver_loadbalancer_domain_name }}"
apiserver_loadbalancer_address: "{{ apiserver_loadbalancer_address }}"
apiserver_loadbalancer_port: "{{ apiserver_loadbalancer_port }}"
use_internal_loadbalancer: "{{ use_internal_loadbalancer }}"
internal_loadbalancer: "{{ internal_loadbalancer }}"
k8s_network_plugin: "{{ k8s_network_plugin }}"
container_runtime: "{{ container_runtime }}"

# File from KubeSpray kubeSpray/inventory/mycluster/group_vars/all/all.yaml
bin_dir: "{{ bin_dir | default('/usr/local/bin') }}"
