---
- name: Updating ingress_nginx_enabled on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^ingress_nginx_enabled: "
    line: "dashboard_enabled: true"
  when: dashboard_enabled | bool == true

- name: Updating ingress_nginx_enabled on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^ingress_nginx_enabled: "
    line: "ingress_nginx_enabled: true"
  when: ingress_nginx_enabled | bool == true

- name: Updating ingress_nginx_host_network on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^# ingress_nginx_host_network: "
    line: "ingress_nginx_host_network: true"
  when: ingress_nginx_enabled | bool == true

- name: Updating helm_enabled on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^helm_enabled: "
    line: "helm_enabled: true"
  when: helm_enabled | bool == true

- name: Updating metrics_server_enabled on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^metrics_server_enabled: "
    line: "metrics_server_enabled: true"
  when: metrics_server_enabled | bool == true

- name: Updating cert_manager_enabled on inventory/sample/group_vars/k8s_cluster/addons.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}roles/tmp/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^cert_manager_enabled: "
    line: "cert_manager_enabled: true"
  when: cert_manager_enabled | bool == true
