---
- name: Updating containerd_storage_dir on inventory/mycluster/group_vars/all/containerd.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}kubespray/inventory/mycluster/group_vars/all/containerd.yml"
    regexp: "^# containerd_storage_dir: "
    line: "containerd_storage_dir: {{ containerd_storage_dir }}"
