---
- name: Updating docker_daemon_graph on inventory/mycluster/group_vars/all/docker.yml
  ansible.builtin.lineinfile:
    path: "{{ jenkins_workspace }}kubespray/inventory/mycluster/group_vars/all/docker.yml"
    regexp: "^docker_daemon_graph: "
    line: "docker_daemon_graph: {{ docker_daemon_graph }}"
