---
- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Clone KubeSpray project
      shell: |
        cd "{{ jenkins_workspace }}roles/"
        pwd
        sleep 10
        git clone https://github.com/kubernetes-sigs/kubespray.git
        cd kubespray/
        pwd
        sleep 10
        git checkout release-2.16
      register: cloning

    - name: Printing cloning output
      debug:
        msg: "{{ cloning.stdout_lines }}"

    - name: Start pipenv shell and install requirements
      command: "{{ item }}"
      with_items:
        - cd "{{ jenkins_workspace }}roles/kubespray/"
        - /usr/local/bin/pipenv shell
        - python3 -m pip install -r requirements.txt
        - exit
      register: pipenv_result

    - name: Printing pipenv_result output
      debug:
        msg: "{{ pipenv_result.stdout_lines }}"
