---
- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Clone KubeSpray project
      shell: "cd {{ jenkins_workspace }}roles/ ; git clone https://github.com/kubernetes-sigs/kubespray.git ; cd kubespray/ ; git checkout release-2.16"

    - name: Start pipenv shell
      shell: "cd {{ jenkins_workspace }}roles/kubespray/ ; pipenv shell ; until pip3 -r requirements.txt ; sleep 5 ;  done ; cp -rfp inventory/sample inventory/mycluster ; sleep  120"
