---
- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Clone KubeSpray project
      shell: |
        cd "{{ jenkins_workspace }}roles/"
        pwd
        sleep 10
        git clone https://github.com/kubernetes-sigs/kubespray.git
        cd kubespray/
        pwd
        sleep 10
        git checkout release-2.16
      register: clonu

    - name: Printing cloning output
      debug:
        msg: "{{ clonu.stdout_lines }}"

    # - name: Start pipenv shell
    #   shell: "cd {{ jenkins_workspace }}roles/kubespray/ && pipenv shell && until pip3 -r requirements.txt ; sleep 5 ;  done && cp -rfp inventory/sample inventory/mycluster && sleep  120"
