---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Cleaning directories
      ansible.builtin.shell: |
        rm -rf /var/log/messages-* /tmp/*
      ignore_errors: True
      args:
        warn: false
      async: 900
      poll: 10

    - name: Running tasks/uninstall.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: uninstall.yaml
