---
- hosts: all
  remote_user: root
  gather_facts: false
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

  tasks:
    - name: Copy inventory/sample to inventory/mycluter
      shell: "date"

- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Copy inventory/sample to inventory/mycluter
      shell: "cp -rfp {{ jenkins_workspace }}roles/kubespray-2.16.0/inventory/sample/ {{ jenkins_workspace }}roles/kubespray-2.16.0/inventory/mycluster/"

    - name: Copy all.yml to mycluster
      copy:
        src: all.yml
        dest: "{{ jenkins_workspace }}roles/kubespray-2.16.0/inventory/sample inventory/mycluster/group_vars/all/all.yml"

    - name: Copy k8s_cluster.yml to mycluster
      copy:
        src: all.yml
        dest: "{{ jenkins_workspace }}roles/kubespray-2.16.0/inventory/sample inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml"

    - name: Running tasks/populate.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: populate.yaml
# - hosts: main-master-node-install
#   remote_user: root
#   gather_facts: false
#   environment:
#     http_proxy: "{{ http_proxy }}"
#     https_proxy: "{{ https_proxy }}"
#     no_proxy: "{{ no_proxy }}"

#   tasks:
#     - name: Clone KubeSpray to /opt/ on main master node
#       shell: "cd /opt/ && git clone -b release-2.16 https://github.com/kubernetes-sigs/kubespray.git"

#     - name: Copy inventory/sample to inventory/mycluter
#       shell: "cp -rfp /opt/kubespray/inventory/sample/ /opt/kubespray/inventory/mycluster"
