---
- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Running tasks/populate.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: populate.yaml

- hosts: kube_control_plane[0]
  remote_user: root
  gather_facts: false
  tasks:
    - name: Making a copy of the current project on one of the control plane nodes
      copy:
        src: "{{ jenkins_workspace }}/roles/tmp/kubespray/"
        dest: /opt/
