---
- hosts: localhost
  remote_user: root
  connection: local
  gather_facts: false
  tasks:
    - name: Running tasks/populate.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: populate.yaml
