---
- hosts: localhost
  remote_user: root
  gather_facts: false
  connection: local
  tasks:
    - name: Running tasks/populate.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: populate.yaml

- hosts: kube_control_plane[0]
  remote_user: root
  gather_facts: false
  tasks:
    - name: Cloning project on master node
      shell: |
        rm -rf /opt/kubespray
        cd /opt/
        git clone https://github.com/kubernetes-sigs/kubespray.git
        cd kubespray
        git checkout release-2.16
        mkdir /opt/kubespray/inventory/mycluster/
      register: gitod

    - name: Making a copy of the kubespray project on one of the control plane nodes
      copy:
        src: "{{ jenkins_workspace }}/roles/tmp/kubespray/inventory/mycluster"
        dest: /opt/kubespray/inventory/
