---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Removing /opt/containerd /opt/cni
      shell: |
        rm -rf /opt/containerd /opt/cni /opt/kubespray /opt/.*
        rm -rf /tmp/* /tmp/.*
      ignore_errors: yes

    - name: Rebooting all nodes using ansible module
      reboot:
        reboot_timeout: 1800
        test_command: whoami
