---
kube_config_dir: /etc/kubernetes
kube_config_dir: /etc/kubernetes/
local_release_dir: "{{ local_release_dir }}"
kube_service_addresses: "{{ kube_service_addresses }}"
kube_pods_subnet: "{{ kube_pods_subnet }}"