---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      
  - name: Running tasks/requirements.yaml instead of 'main'
    import_role:
      name: ../
      tasks_from: requirements.yaml